pipeline {
    agent any
    environment {
        IMAGE_NAME = 'samiwin1/certification-service'
        IMAGE_TAG = 'latest'
        DOCKER_CREDS = credentials('dockerhub-credentials')
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Code checked out'
            }
        }
        stage('Build') {
            steps {
                dir('certification-service') {
                    bat 'mvn clean package -DskipTests -B'
                }
            }
        }
        stage('Tests') {
            steps {
                dir('certification-service') {
                    bat 'mvn test -B'
                }
            }
        }
        stage('Docker Build & Push') {
            steps {
                dir('certification-service') {
                    bat "docker build -t %IMAGE_NAME%:%IMAGE_TAG% ."
                    bat "docker login -u %DOCKER_CREDS_USR% -p %DOCKER_CREDS_PSW%"
                    bat "docker push %IMAGE_NAME%:%IMAGE_TAG%"
                }
            }
        }
    }
    post {
        success { echo 'Pipeline succeeded!' }
        failure { echo 'Pipeline failed.' }
    }
}
