# Values are base64 encoded
# rootpass -> cm9vdHBhc3M=
# appuser -> YXBwdXNlcg==
# apppassword -> YXBwcGFzc3dvcmQ=
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: pidev
type: Opaque
data:
  root-password: cm9vdHBhc3M=
  username: YXBwdXNlcg==
  password: YXBwcGFzc3dvcmQ=
