apiVersion: apps/v1
kind: Deployment
metadata:
  name: certification-service
  namespace: pidev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: certification-service
  template:
    metadata:
      labels:
        app: certification-service
    spec:
      containers:
        - name: certification-service
          image: pidev/certification-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DB_HOST
              value: mysql-certification-service
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_NAME_CERTIFICATION
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: JWT_SECRET
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3
