apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-certification-pvc
  namespace: pidev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-certification
  namespace: pidev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-certification
  template:
    metadata:
      labels:
        app: mysql-certification
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_NAME_CERTIFICATION
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-certification-pvc
