apiVersion: v1
kind: Service
metadata:
  name: certification-service
  namespace: pidev
spec:
  selector:
    app: certification-service
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
