apiVersion: v1
kind: Service
metadata:
  name: mysql-certification-service
  namespace: pidev
spec:
  selector:
    app: mysql-certification
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
